version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: mysql_shop_system
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: shop_system_db
      MYSQL_DEBUG: "d,info,err,warn"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin_shop_system
    environment:
      PMA_ARBITRARY: 1
    ports:
      - "8081:80"
    depends_on:
      - db

volumes:
  mysql_data:
